# Generated by Django 6.0.1 on 2026-01-20 05:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionWiseMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_question_marks', to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_marks', to='marks.marks')),
            ],
            options={
                'verbose_name': 'Question Wise Marks',
                'verbose_name_plural': 'Question Wise Marks',
                'db_table': 'question_wise_marks',
                'ordering': ['marks', 'question_number'],
                'unique_together': {('marks', 'question_number')},
            },
        ),
    ]
