# Generated by Django 5.0.1 on 2026-01-18 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_commands/%Y/%m/%d/')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, choices=[('ENTER_MARKS', 'Enter Marks'), ('MARK_ATTENDANCE', 'Mark Attendance'), ('VIEW_STUDENT', 'View Student Details'), ('UNKNOWN', 'Unknown Intent')], max_length=20, null=True)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('confirmation_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='PENDING_CONFIRMATION', max_length=25)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Command',
                'verbose_name_plural': 'Voice Commands',
                'db_table': 'voice_commands',
                'ordering': ['-created_at'],
            },
        ),
    ]
