# Generated by Django 5.0.1 on 2026-01-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecommand',
            name='intent',
            field=models.CharField(blank=True, choices=[('ENTER_MARKS', 'Enter Marks'), ('MARK_ATTENDANCE', 'Mark Attendance'), ('VIEW_STUDENT', 'View Student Details'), ('NAVIGATE_MARKS', 'Navigate to Marks'), ('NAVIGATE_ATTENDANCE', 'Navigate to Attendance'), ('OPEN_MARKS_SHEET', 'Open Marks Sheet'), ('OPEN_ATTENDANCE_SHEET', 'Open Attendance Sheet'), ('UPDATE_MARKS', 'Update Marks in Sheet'), ('UNKNOWN', 'Unknown Intent')], max_length=30, null=True),
        ),
    ]
