# Generated by Django 4.2.11 on 2026-02-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_processing', '0002_alter_voicecommand_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecommand',
            name='intent',
            field=models.CharField(blank=True, choices=[('ENTER_MARKS', 'Enter Marks'), ('MARK_ATTENDANCE', 'Mark Attendance'), ('VIEW_STUDENT', 'View Student Details'), ('NAVIGATE_MARKS', 'Navigate to Marks'), ('NAVIGATE_ATTENDANCE', 'Navigate to Attendance'), ('OPEN_MARKS_SHEET', 'Open Marks Sheet'), ('OPEN_ATTENDANCE_SHEET', 'Open Attendance Sheet'), ('UPDATE_MARKS', 'Update Marks in Sheet'), ('COLLECT_FEE', 'Collect Fee'), ('OPEN_FEE_PAGE', 'Open Fee Page'), ('SHOW_DEFAULTERS', 'Show Defaulters'), ('TODAY_COLLECTION', 'Today Collection'), ('NAVIGATE_FEE_REPORTS', 'Navigate to Fee Reports'), ('UNKNOWN', 'Unknown Intent')], max_length=35, null=True),
        ),
    ]
